### ISSUE TITLE
Incomplete tool navigation

### ISSUE THREAD

**Issue by chenyu-zyq** [ckeditor/ckeditor4-vue#118]
There are no modify color buttons and center buttons in use

**Comment by KarolDawidziuk** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests or bug reports](https://github.com/ckeditor/ckeditor4-vue/issues/new). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
