### ISSUE TITLE
在 ckeditor4-vue 中工具栏中没有颜色控制器、文字对齐方式、修改字体大小等功能

### ISSUE THREAD

**Issue by chenyu-zyq** [ckeditor/ckeditor4-vue#119]
## Are you reporting a feature request or a bug?
在 ckeditor4-vue 中工具栏中没有颜色控制器、文字对齐方式、修改字体大小等功能

## Provide detailed reproduction steps (if any)

1. 配置
![image](https://user-images.githubusercontent.com/42834279/134606530-ea936b6c-d4d2-47eb-ac2e-ca2383d56997.png)

2. …
3. …

### Expected result

*What is the expected result of the above steps?*
![image](https://user-images.githubusercontent.com/42834279/134606872-a3dee2ea-4906-4a4d-b0a7-0c4e4cff8c6d.png)

### Actual result

*What is the actual result of the above steps?*
![image](https://user-images.githubusercontent.com/42834279/134606833-0366208d-eb05-4141-9137-f5665439eb46.png)

**Comment by KarolDawidziuk** [comment]
Hi, @chenyu-zyq 

Sorry, but I don't understand Chinese.
Please create an issue in English.
