### ISSUE TITLE
Is keep-alive can support now?

### ISSUE THREAD

**Issue by ljj501** [ckeditor/ckeditor4-vue#136]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor4-vue/blob/master/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_issues_readme.html) on the tracker, and open a new issue using the template as this one is being closed now.
