### ISSUE TITLE
Multiple CKeditor don't trigger focus and blur

### ISSUE THREAD

**Issue by ka5itoshka** [ckeditor/ckeditor4-vue#141]
Hi. I have a small project, where i need to use Ckeditor 4 with VueJS 2.

So i downloaded all scripts from official website, but have a big problem: blur and focus event works only with last editor at the page.

Here my code, where i trying to initialize editor at the page.

<ckeditor
@blur="logEvent('blur', $event)"
:config="CKeditorConfig"
:value="editorData"
></ckeditor>

<ckeditor
@blur="logEvent('blur', $event)"
:config="CKeditorConfig"
:value="editorData"
></ckeditor>

I tried to debug official ckeditor-vuejs port, and saw that each time my editor have same name.

UPDATE. Found a fix, need an init ckeditor as another component (textcomponent -> ckeditor):
<template>
<ckeditor 
	 v-model="$parent.fields[module][field][value]" 
	 :config="CKeditorConfig"
	 @input="$emit('change')">
 </ckeditor>
</template>

**Comment by jacekbogdanski** [comment]
@ka5itoshka I did a very simple demo verifying events propagation for blur and it looks like everything works correctly - https://codesandbox.io/s/ckeditor4-vue-bug-report-forked-r4z952?file=/src/App.vue

Note that these events are propagated within the same component instance, but that's basically how Vue works. If you see that there may be other issues I didn't catch up on from your report, please prepare a minimal demo using some online editor like https://codesandbox.io/s/ekuyo (you can fork that one, it already includes boilerplate for CKEditor 4 component).
