### ISSUE TITLE
Documentation code sample property names

### ISSUE THREAD

**Issue by bontibon** [ckeditor/ckeditor4-vue#16]
Non-kebab-case property names are incorrectly used in the documentation code samples for the following properties:

- editorUrl → editor-url
- readOnly → read-only

**Comment by f1ames** [comment]
@bontibon, could you link to a place where you have found the mistake in the docs, I see we have some inconsistency [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#read-only), but not sure about `editorUrl` :thinking: 

We are using `editorUrl` and `readOnly` prop names, do you mean it should be `editor-url` and `read-only` to be consistent with Vue convention?

**Comment by bontibon** [comment]
The docs for [editorUrl](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#editorurl) and the code sample for [read-only](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#read-only) are incorrect.

When using `editorUrl` and `readOnly` instead of `editor-url` and `read-only`, respectively, the following warnings are emitted in the browser console:

> [Vue tip]: Prop "editorurl" is passed to component <Anonymous>, but the declared prop name is "editorUrl". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "editor-url" instead of "editorUrl".

> [Vue tip]: Prop "readonly" is passed to component <Anonymous>, but the declared prop name is "readOnly". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "read-only" instead of "readOnly".

**Comment by f1ames** [comment]
Thanks for the clarification @bontibon! We will fix it soon.

**Comment by f1ames** [comment]
Fixed with ckeditor/ckeditor4-docs@08c7231.
