### ISSUE TITLE
Feature Request: Insert Video in the content

### ISSUE THREAD

**Issue by blpraveen** [ckeditor/ckeditor4-vue#160]
## Are you reporting a feature request or a bug?
Feature Request

## Provide detailed reproduction steps (if any)

Feature Request. How can I insert video within the content
### Expected result
Should be able to insert video?
*What is the expected result of the above steps?*

## Other details

* Browser:Edge
* OS:Windows
* Integration version: …
* CKEditor version: 4
* Installed CKEditor plugins:No

**Comment by blpraveen** [comment]
Hi,
I tried
```
CKEditor.plugins.addExternal( 'html5video', 'https://raw.githack.com/bahriddin/ckeditor-html5-video/master/html5video/plugin.js' );
```
it is giving error 
```
Cannot read properties of undefined (reading 'addExternal')
```

**Comment by jacekbogdanski** [comment]
CKEditor 4 reached it's end of life and we no longer provide new features. You can read https://ckeditor.com/docs/ckeditor4/latest/support/licensing/extended-support-model.html for more info.
