### ISSUE TITLE
CKEditor version is not secure

### ISSUE THREAD

**Issue by rakesh-bitcot** [ckeditor/ckeditor4-vue#162]
Hello, I am facing the below issue please check this issue and fix it as soon as possible.

Issue :  This CKEditor 4.22.1 (Standard) version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.25.0-lts.

**Comment by jacekbogdanski** [comment]
Please see https://github.com/ckeditor/ckeditor4/issues/5519
