### ISSUE TITLE
Usage of document editor in vuejs

### ISSUE THREAD

**Issue by JoeWitchy** [ckeditor/ckeditor4-vue#18]
Hey guys, I'm kinda new to ckeditor and I'm using vuejs as a framework of choice. I was easily able to run ckeditor but I'm trying to use the document editor and I'm not able to find any solution as to how to achieve it. Would be great if someone can help me out on this. The picture that i uploaded is the kind of editor I would like to use and I'm not able to figure out how to get this. Have a great day.
![Capture](https://user-images.githubusercontent.com/54702110/76241500-17db1080-625b-11ea-910a-043d05d6d7ae.PNG)

**Comment by f1ames** [comment]
Hello @JoeWitchy,

thanks for reporting in a correct repository:+1: The [document editor](https://ckeditor.com/ckeditor-4/demo/#document) uses customized config which changes default set of plugins/features and toolbar buttons. You may refer to [Toolbar Configuration guide](https://ckeditor.com/docs/ckeditor4/latest/features/toolbar.html) to see how it can be adjusted.

As for document editor, the exact config used on the demo page looks like this:

```plaintext
{
    toolbar: [
        { name: 'document', items: [ 'Print' ] },
        { name: 'clipboard', items: [ 'Undo', 'Redo' ] },
        { name: 'styles', items: [ 'Format', 'Font', 'FontSize' ] },
        { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat', 'CopyFormatting' ] },
        { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
        { name: 'align', items: [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
        { name: 'links', items: [ 'Link', 'Unlink' ] },
        { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] },
        { name: 'insert', items: [ 'Image', 'Table' ] },
        { name: 'tools', items: [ 'Maximize' ] },
        { name: 'editing', items: [ 'Scayt' ] }
    ],
    removePlugins: 'autoembed,embedsemantic,image2,sourcedialog,showborders',
    disallowedContent: 'img{width,height,float}',
    extraAllowedContent: 'img[width,height,align]'
}
```
