### ISSUE TITLE
Two-way data binding not working on view-source mode

### ISSUE THREAD

**Issue by lookhill** [ckeditor/ckeditor4-vue#23]
While in view source-mode, the two-way data binding is not working and the data is not updating when you write in the textarea.
Once you switch back to WYSYWYG mode the data is then refreshed.

You can test it out on the official demo link:
https://ckeditor.com/docs/ckeditor4/latest/examples/vue.html#/2-way-binding

clicking on the view-source button and typing something doesn't update the "Rendered content" box.

It would be nice to keep the two-way binding active while in view-source mode too.

Thanks for the great work your're doing!

**Comment by jacekbogdanski** [comment]
Hello,

it's a design issue. Inside CKEditor 4, we are treating different modes as separate input elements and source editing is not supported by undo plugin required to detect editor changes. To keep editor and integration consistent, it's recommended to not update v-model in source mode during typing.
