### ISSUE TITLE
Not all toolbar buttons included?

### ISSUE THREAD

**Issue by EasonLin0716** [ckeditor/ckeditor4-vue#26]
Hello, 
I installed and used it as a component
`npm install ckeditor4-vue`

and the code is the same with example on [official site](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html) 
```
<template>
    <div id="app">
        <ckeditor v-model="editorData" :config="editorConfig"></ckeditor>
    </div>
</template>

<script>
    export default {
        name: 'app',
        data() {
            return {
                editorData: '<p>Content of the editor.</p>',
                editorConfig: {
                    // The configuration of the editor.
                }
            };
        }
    }
</script>
```
But my toolbar is not the same as it is with
![68747470733a2f2f632e636b736f757263652e636f6d2f612f312f696d672f6e706d2f636b656469746f72342e706e67](https://user-images.githubusercontent.com/48944243/78521012-1d485e00-77fb-11ea-8ae9-df6faffbecb9.png)

I tried the instruction on [Toolbar Configuration](https://ckeditor.com/docs/ckeditor4/latest/features/toolbar.html)

But my toolbar still looks like this:
![1231258](https://user-images.githubusercontent.com/48944243/78521089-4e289300-77fb-11ea-951f-d870d7691709.JPG)
Some toolbar buttons are not included in my ckeditor
Is there anyways I can solve this problem? Thank you.

**Comment by jacekbogdanski** [comment]
Vue integration uses `standard-all` CKEditor 4 preset which has a limited number of plugins, you can see a comparison here: https://ckeditor.com/cke4/presets-all

The attached screenshot has been created with `full-all` preset, which you can use by updating integration CDN URL: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#editorurl

e.g.

```html
<ckeditor editorUrl="https://cdn.ckeditor.com/4.14.0/full-all/ckeditor.js"></ckeditor>
```
