### ISSUE TITLE
CKEditor 5 with Vuejs 1.x cdn project

### ISSUE THREAD

**Issue by shreesalunke** [ckeditor/ckeditor4-vue#27]
Hi There
any chance to use CKEditor 5 component in VueJS 1.x project with CDN
If possible can you please provide an example link 
Thanks

**Comment by Dumluregn** [comment]
Hello, please note that it's **CKEditor 4** Vue repo. Please go to [ckeditor5-vue](https://github.com/ckeditor/ckeditor5-vue/issues) instead.
