### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-vue#3]
We need to make sure if IE11 is supported by the integration. It may require some additional polyfill but should be also tested.

**Comment by jacekbogdanski** [comment]
We find out that IE11 support could be easily implemented by extending bundle builder with additional environment polyfills. However, due to a significantly bigger bundle file when IE11 support is enabled, the legacy browser will be supported by importing a special bundle file instead of the default one. I'm closing the issue now as IE11 support will be provided as a part of the first version of the integration, so no need to keep it as a separate ticket.

Information about the legacy browser bundle version will be provided with appropriate docs.

**Comment by f1ames** [comment]
> However, due to a significantly bigger bundle file when IE11 support is enabled, the legacy browser will be supported by importing a special bundle file instead of the default one.

I haven't dive into details of the above yet and how it exactly works. AFAIU now we will have two files, one for modern browsers and one for legacy ones (IE11). Have you considered a different approach where base file is always the same and the polyfills file can be added by adding/importing additional file? So instead of switching files you have always one, same file and if you need IE11 support you can attach polyfills (always or just dynamically for IE11)?

**Comment by jacekbogdanski** [comment]
We didn't discuss it as support is provided by https://babeljs.io/docs/en/babel-preset-env so I'm not sure if it's possible. It looks like an interesting approach, but in the end, does it not comes down to the same for both methods? You could always check if it's IE11 and chooses correct file import:

* with polyfill
```
if ( IE11 ) {
  include polyfill
}
```
* with separate legacy file

```
if ( IE11 ) {
  include legacy file
} else {
  include normal file
}
```
but agree polyfill approach looks cleaner :thinking: @Comandeer do you have some knowledge if polyfills can be extracted as a separate chunk when building bundle with webpack + babel-preset-env?

**Comment by Comandeer** [comment]
I think it is possible, but convoluted enough to be not feasible. I'm afraid that generating polyfills as separate bundle would disable Babel optimisations and all polyfills, including unnecessary, will be bundled.
