### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-vue#39]
Currently it's blank. 

It should remind the one from the [ckeditor4 repo](https://raw.githubusercontent.com/ckeditor/ckeditor4/major/.github/ISSUE_TEMPLATE/1-bug-report.md) except for the link for reproducing issues (should be adjusted to Vue).

**Comment by jacekbogdanski** [comment]
I did it some time ago, didn't notice the issue.
