### ISSUE TITLE
Failing setData Edge tests

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-vue#4]
`setData` tests fail on Edge due to some Permission Denied error - https://github.com/ckeditor/ckeditor4-vue/blob/65c152b7c2c40eb3441193671a269c447dd80939/tests/component.js#L289-L297

I didn't notice any issue with manual testing on Edge but we need to make sure nothing is broken and verify why actually the tests fail.

**Comment by f1ames** [comment]
I think since Edge migrated to Chromium engine we can close this as it is no longer an issue.
