### ISSUE TITLE
Remove reference to editor instance inside vue component scope

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4-vue#5]
It should be possible to register all necessary listeners directly inside the mount function without preserving the reference to editor's instance in the Vue component as `this.instance`:
* https://vuejs.org/v2/guide/components-edge-cases.html#Programmatic-Event-Listeners
* https://vuejs.org/v2/api/#vm-watch

**Comment by jacekbogdanski** [comment]
Editor instance is enabled by design - it may be used by users to customize CKEditor (e.g. by registering own listeners) and needed in unit tests. Could you tell why you see it as an issue?

**Comment by msamsel** [comment]
>  it may be used by users to customize CKEditor (e.g. by registering own listeners) and needed in unit tests

That's a valid point.

I just saw that vue docs suggest adding such hooks dynamically. I think it might also prevent using `$_destroyed` flag.

**Comment by jacekbogdanski** [comment]
Thanks for the response. So, for the time being, let's treat it as by design and see how it works.
