### ISSUE TITLE
CI is red due to Safari errors

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-vue#59]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

Recently CI turned red due to some Safari error from what I can see :thinking: 

![image](https://user-images.githubusercontent.com/1061942/92616614-bace1f00-f2be-11ea-8c7c-bfb20a1aad13.png)

Last green build - https://github.com/ckeditor/ckeditor4-vue/commit/2ff96a975798163268586a8976611e4ef46884be
First red build - https://github.com/ckeditor/ckeditor4-vue/commit/49d3872f3b6f4dfb594f5f68f6c8a8bc291a97e8 (restarted to see if it's not random)

**Comment by jacekbogdanski** [comment]
Seems to fails randomly - https://travis-ci.org/github/ckeditor/ckeditor4-vue/builds/733608430

I guess karma timeout could be just too strict for Browser Stack.

**Comment by f1ames** [comment]
> Seems to fails randomly - https://travis-ci.org/github/ckeditor/ckeditor4-vue/builds/733608430
> 
> I guess karma timeout could be just too strict for Browser Stack.

Maybe we can just increase karma timeout and see if it still fails?

**Comment by jacekbogdanski** [comment]
Let's check out how it works with 3000ms and if the issue occurs again we can revisit this issue for a higher timeout or some fix.

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4-vue/compare/cb4ee3af11bb...681e3cc1e1af

Let's check if works as expected and if the issue occurs again, reopen this ticket.
