### ISSUE TITLE
Unable to configure local plugin when using ckeditor from cdn

### ISSUE THREAD

**Issue by jmalatia** [ckeditor/ckeditor4-vue#60]
There is no way we can see to configure the path for a local custom plugin when using ckeditor from cdn.

Without vue, the normal process would be:
```
<script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
<script>
    CKEDITOR.plugins.addExternal('divarea', '/path-to-local-plugin/plugins/divarea/', 'plugin.js');
</script>
<script>
    CKEDITOR.replace("HtmlContent", {
        customConfig: 'ckEditorLocalPathToConfig/config.js',
    });
</script>
```
Then in config.js:
```
CKEDITOR.editorConfig = function( config ) {
    config.extraPlugins = 'divarea';
}
```

Seems like ckeditor4-vue needs something like a `pluginAddExternal` prop added to the component and then invoked in it's code before it calls replace?

**Comment by jacekbogdanski** [comment]
@jmalatia CKEditor 4 Vue integration won't load `CKEDITOR` namespace if you do it yourself. That means that you could still use CDN script externally to have access to the `CKEDITOR` object, so you can add an external plugin before the editor instance will be initialized. Please, take a look at https://codepen.io/jacekbogdanski/pen/vYGjLxe where I'm using `standard` editor preset without `editorplaceholder` plugin, but I can still load it using `CKEDITOR.plugins.addExternal`.

However, I think it's a good idea to introduce some method which would allow us to access `CKEDITOR` namespace before initializing editors for use cases like the above. I will create a separate ticket for that.

**Comment by jmalatia** [comment]
@jacekbogdanski  We are using this in a vue SPA with single file components and `ckeditor.component` so the codepen will not work for us.  But the new ticket [#61](https://github.com/ckeditor/ckeditor4-vue/issues/61) you opened is exactly what we need.  Thanks.
