### ISSUE TITLE
Vue docs

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4-vue#7]
Before publishing integration we need nicely written docs similar to [Angular](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html) and [React](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html) one.

**Comment by f1ames** [comment]
Fixed with https://github.com/ckeditor/ckeditor4-docs/commit/1f6a4204a31550f94140e559cdaf356084905076.
