### ISSUE TITLE
Enable text alignment

### ISSUE THREAD

**Issue by arungpisyadi** [ckeditor/ckeditor4-vue#89]
There is no information on how to enable "text-alignment". I had to find it the hard way.
Please inform or give an example of how to enable plugins that by default are not enabled in CKEditor 4.
Something like the below should be enough.
`editorConfig: { extraPlugins: 'justify, language' },`

**Comment by Dumluregn** [comment]
In the docs of the [`config` property](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#config) we show how to adjust the content of the toolbar. Adding and removing plugins is completely analogous. It isn't possible to add an example for each configuration option change and I think it is specified well enough.

**Comment by arungpisyadi** [comment]
I think it still worth mentioning in the document, especially for those who have not used CKEditor before like me.

Thank you though for your reply. 😇🙏
