### ISSUE TITLE
Missing toolbar action

### ISSUE THREAD

**Issue by narendra087** [ckeditor/ckeditor4-vue#97]
BUG
In my project there are action that missing on the CKEditor toolbar.
this is my toolbar config.

![image](https://user-images.githubusercontent.com/19150149/111731414-01bc5300-88a6-11eb-99c7-a99697905746.png)

### Expected result

![image](https://user-images.githubusercontent.com/19150149/111731507-303a2e00-88a6-11eb-86f5-9331a70e8d99.png)

### Actual result

![image](https://user-images.githubusercontent.com/19150149/111731533-3e884a00-88a6-11eb-9535-e60540d41829.png)

Any ideas how to fix it? thanks.

**Comment by Dumluregn** [comment]
Hello, Vue integration by default uses [`standard-all` preset](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#editor-url), while the CDN sample - `full-all` one. You can simply change the CKEditor 4 preset used with [`editorUrl` directive](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html#editor-url) and set the value to `https://cdn.ckeditor.com/4.16.0/full-all/ckeditor.js` - that should enable all the buttons without the need to alter the toolbar config itself.
